### ISSUE TITLE
Could not bind the data source in Joomla\CMS\Table\Content::bind()

### ISSUE THREAD

**Issue by modernmagic** [ruchikanagarkar/Update-bulk-articles-in-joomla-using-php#1]
When I run your file here:  https://staging2.primocraft.com/save.php

I get the following and the articles do not seem to be updated:

Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.Could not bind the data source in Joomla\CMS\Table\Content::bind(), the source must be an array or object but a "NULL" was given.
article updated - 71

article updated - 72

article updated - 73

article updated - 74

article updated - 75

article updated - 76

article updated - 77

article updated - 78

article updated - 79

article updated - 80

article updated - 81

article updated - 82

article updated - 83

article updated - 84

article updated - 85

article updated - 86

article updated - 87

article updated - 88

article updated - 89

article updated - 90

article updated - 91

article updated - 92

article updated - 93

article updated - 94

article updated - 95

article updated - 96

article updated - 97

article updated - 98

article updated - 99

article updated - 100

article updated - 101

article updated - 102

article updated - 103

article updated - 104

article updated - 105

article updated - 106

article updated - 107

article updated - 108

article updated - 109

article updated - 110

article updated - 111

article updated - 112

article updated - 113

article updated - 114

article updated - 115

article updated - 116

article updated - 117

article updated - 118

article updated - 119

article updated - 120

article updated - 121

article updated - 122

article updated - 123

article updated - 124

article updated - 125

article updated - 126

article updated - 127

article updated - 128

article updated - 129

article updated - 130

article updated - 131

article updated - 132

article updated - 133

article updated - 134

article updated - 135

article updated - 136

article updated - 137

article updated - 138

article updated - 139

article updated - 140

article updated - 141

article updated - 142

article updated - 143

article updated - 144

article updated - 145

article updated - 146

article updated - 147

article updated - 148

article updated - 149

article updated - 150

article updated - 151

article updated - 152

article updated - 153

article updated - 154

article updated - 155

article updated - 156

article updated - 157

article updated - 158

article updated - 159

article updated - 160

article updated - 161

article updated - 162

article updated - 163

article updated - 164

article updated - 165

article updated - 166

article updated - 167

article updated - 168

article updated - 169

article updated - 170

article updated - 171

article updated - 172

article updated - 173

article updated - 174

article updated - 175

article updated - 176

article updated - 177

article updated - 178

article updated - 179

article updated - 180

article updated - 181

article updated - 182

article updated - 183

article updated - 184

article updated - 185

article updated - 186

article updated - 187

article updated - 188

article updated - 189

article updated - 190

article updated - 191

article updated - 192

article updated - 193

article updated - 194

article updated - 195

article updated - 196

article updated - 197

article updated - 198

article updated - 199

article updated - 200

article updated - 201

article updated - 202

article updated - 203

article updated - 204

article updated - 205

article updated - 206

article updated - 207

article updated - 208

article updated - 209

article updated - 210

article updated - 211

article updated - 212

article updated - 213

article updated - 214

article updated - 215

article updated - 216

article updated - 217

article updated - 218

article updated - 219

article updated - 220

article updated - 221

article updated - 222

article updated - 223

article updated - 224

article updated - 225

article updated - 226

article updated - 227

article updated - 228

article updated - 229

article updated - 230

article updated - 231

article updated - 232

article updated - 233

article updated - 234

article updated - 235

article updated - 236

article updated - 237

article updated - 238

article updated - 239

article updated - 240

article updated - 241

article updated - 242

article updated - 243

article updated - 244

article updated - 245

article updated - 246

article updated - 247

article updated - 248

article updated - 249

article updated - 250

article updated - 251

article updated - 252

article updated - 253

article updated - 254

article updated - 255

article updated - 256

article updated - 257

article updated - 258

article updated - 259

article updated - 260

article updated - 261

article updated - 262

article updated - 263

article updated - 264

article updated - 265

article updated - 266

Error: Class 'JDocumentRaw' not found: Class 'JText' not found

**Comment by ruchikanagarkar** [comment]
can you tell me what starting index and ending index of the article id you are using?

like here article id starts from 1 and ends at 1000. 

```
for($i=1; $i<1000;$i++){
	$query = $db->getQuery(true);
	$query->select('*')->from('#__content')->where('id='.$i.'');
	$update_data = $db->setQuery($query)->loadAssoc();
	if(!$article_model->save($update_data)){
	    echo $err_msg = $article_model->getError();
	}else{
		echo '<p>article updated - '.$i.'</p>';
	}
}
```

**Comment by modernmagic** [comment]
I'm so sorry, but I can't remember what I did.  However, in the end it all worked out.  Thank you for the reply.

**Comment by ruchikanagarkar** [comment]
no worries. Glad it worked for you 👍 I think the article id must have been incorrect due to which it was giving null exception
